log:
  level: debug

oauth:
  client_id: team289
  # client_secret: 123
  oauth_providers:
    - name: vbank
      base_url: 'https://vbank.open.bankingapi.ru/auth/bank-token'
    - name: sbank
      base_url: 'https://sbank.open.bankingapi.ru/auth/bank-token'
    - name: abank
      base_url: 'https://abank.open.bankingapi.ru/auth/bank-token'

cache: 
  initial_capacity: 10000
  maximum_size: 100000

http: 
  addr: "localhost:51515"

postgres:
  user: lima
  password: dfltpgpswrd
  host: localhost
  port: 5432
  db_name: lima
  ssl_mode: disable
  pool_max_conns: 4
  pool_min_conns: 0
  pool_max_conn_lifetime: 20m
  pool_max_conn_idle_time: 30m
  pool_health_check_period: 60s
  pool_max_conn_lifetime_jitter: 1ms